stages:
  - testbuild
  - deploy

Test build:
  image: node:18-alpine
  stage: testbuild
  only:
    - main
  script:
    - >
      if [ -f yarn.lock ]; then yarn --frozen-lockfile;
      elif [ -f package-lock.json ]; then npm i;
      elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile;
      else echo "Lockfile not found." && exit 1;
      fi
    - yarn build

Deploy to production:
  image: sawanon/sawanon-ssh
  stage: deploy
  only:
    - master
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $USER@$DEPLOY_HOST "
      git clone https://gitlab.powermap.live/peelawit/aaipico-ai-frontend.git &&
      docker compose -f aaipico-ai-frontend/docker-compose.yaml up --force-recreate --build -d &&
      docker image prune -f &&
      docker builder prune -f &&
      rm -r -f aaipico-ai-frontend"
